### ISSUE TITLE
关于交叉验证

### ISSUE THREAD

**Issue by ShawnyXiao** [xing89qs/CCF_Product#2]
您好！

请问，您是否有做**线下的交叉验证**呢？具体是怎么做的？麻烦您解答一下~

**Comment by xing89qs** [comment]
这个比赛是按时间切分数据的，不建议做交叉验证，线下选择最后一个月做验证集，倒数第二个月之前的提取特征做训练集即可。

**Comment by ShawnyXiao** [comment]
意思是倒数第一个月做验证集，倒数第二个月做训练集；还是倒数第一个月做验证集，其他数据做训练集？

这样的话对于线上提交的结果，是取所有训练数据做训练集，还是只取倒数第一个月做训练集？

**Comment by xing89qs** [comment]
倒数第一个月做验证集，训练集的话要看数据有时候是倒数第二个月好，有时候倒数第二+第三好，有时候全部好，这需要各自做测试或者看个人经验吧，提取特征时不要leak就好。
线上的话同上，建议线上线下按同样的样本选择方法，线上线下不同步的概率小一些。

**Comment by ShawnyXiao** [comment]
非常感谢您的回答！
